### ISSUE TITLE
Sniff to automatically use `::class`-expressions

### ISSUE THREAD

**Issue by Ma27** [mayflower/mo4-coding-standard#131]
### Type of issue

* [ ] Bug in MO4 sniffer rule.
* [ ] Bug in MO4 auto-fixer.
* [ ] Bug in MO4 documentation.
* [ ] Request to extend MO4 sniffer with specific rule.
* [x] Request to extend MO4 auto-fixer for specific rule.
* [ ] Request to extend MO4 documentation.
* [ ] Other (explain):

### Description

In the codebase of a certain customer we have a lot of classes which define a `NAME` constant which contains the own class-name (`public const NAME = self::class;` or previously `const NAME = __CLASS__;`). This was used to reference class-names across the codebase without having to change those in case of a rename or a movement to another namespace (if the class or namespace changes, the IDE takes care of it).

However since PHP 5.5 there's the [`::class`-constant](https://thephp.cc/news/2013/06/php-5-5-new-class-constant) which makes this obsolete.  I'm pretty sure that a lot of codebases with components that were implemented before PHP 5.5 do something similar. Therefore I'd like to see a fixer which automatically detects constants that define the class's name, remove this const and replaces all occurrences across of this `NAME` constant the codebase with `::class`.

IMHO a fixer is sufficient as PHP5 is mostly dead by now, so no new code should have such a problem :) 

### Technical details

* PHP version: not relevant
* PHPCS version:
* MO4 version:
* OS: not relevant

**Comment by mmoll** [comment]
Unsure if this is a PHPCS or rather a rector task.

**Comment by Khartir** [comment]
Since CodeSniffer only knows about the current file it is checking, it wouldn't be able to fix this. So there could only be a check for this, not a fixer.

**Comment by Ma27** [comment]
I see. I'll retract this request then :)
