### ISSUE TITLE
Add PSR12.Traits.UseDeclaration

### ISSUE THREAD

**Issue by Khartir** [mayflower/mo4-coding-standard#146]
### Type of issue

* [ ] Bug in MO4 sniffer rule.
* [ ] Bug in MO4 auto-fixer.
* [ ] Bug in MO4 documentation.
* [x] Request to extend MO4 sniffer with specific rule.
* [ ] Request to extend MO4 auto-fixer for specific rule.
* [ ] Request to extend MO4 documentation.
* [ ] Other (explain):

### Description

#144 does not enforce a blank line between trait imports and class constants.
This would be enforced by `PSR12.Traits.UseDeclaration`, which is available with phpcs `3.5.0`.

**Comment by mmoll** [comment]
@Khartir Please open a PR which also raises the respective requirement.
