### ISSUE TITLE
curly brackets not working correctly in every case

### ISSUE THREAD

**Issue by andythedandy** [mayflower/mo4-coding-standard#3]
Problem with following composition:
$flow->write("InputFile: {$adapter->getComputedPath($inputFile->getKey())}\n");

At the moment PhpStorm 8.0.3 don't recognize this kind of bracket correctly. 
It say: "[x] must surround variable $inputFile with {}"

Regards.
Andy

**Comment by calbrecht** [comment]
Another testcase:
"{$good[$fail]}"
