### ISSUE TITLE
variable alignment sniff fails on multiple equal signs per row

### ISSUE THREAD

**Issue by Ma27** [mayflower/mo4-coding-standard#32]
imagine the following code snippet:

``` php
$assetWidth   = $assetHeight = 30;
$previewWidth = 600;
```

Although the lines are aligned properly (are they??) the alignment sniff complains about wrong alignment

**Comment by Ma27** [comment]
after thinking a little bit about this I guess that we simply didn't specify this case.
It should be discussed IMHO which style we want to have.

I can imagine three possibilities:
``` php
$assetWidth   = $assetHeight = 30;
$previewWidth = 600;
```

``` php
$assetWidth   = $assetHeight = 30;
$previewWidth                = 600;
```

``` php
$assetWidth   =
$assetHeight  = 30;
$previewWidth = 600;
```

ping @xalopp @ritters @andythedandy @periklis @calbrecht @elger @danielhallmann

**Comment by andythedandy** [comment]
I like 
```
$assetWidth   = $assetHeight = 30;
$previewWidth = 600;
```

**Comment by Ma27** [comment]
I'd go for the third alternative.
The thing is that if we have to assign many variables to one value, we may exceed the 120 char limit, so the third solution would surely solve this issue.
Here one code snippet of the doctrine core to show: https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/UnitOfWork.php#L421-L431

**Comment by calbrecht** [comment]
+1 the third albeit it seems wrong to write such expressions.

**Comment by xalopp** [comment]
MultipleStatementAlignment is imported from PHPCS it self. The current implementation won't complain about
```
$assetWidth   = $assetHeight = 30;
$previewWidth = 600;
```

So I close this issue 😄
