### ISSUE TITLE
There should be a sniff to detect superfluous whitespace

### ISSUE THREAD

**Issue by mmoll** [mayflower/mo4-coding-standard#41]
```php
$sheet1 =  $excel->getSheet(0);
```
note the two spaces after the =

**Comment by xalopp** [comment]
Would [Squiz.WhiteSpace.OperatorSpacing](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php satisfy your requirements?

If so, we can import that specific sniff in MO4

**Comment by mmoll** [comment]
I guess I/we need to have a good look onto all these WhiteSpace sniffs 🐽

**Comment by mmoll** [comment]
I found one case where that once is not ideal, but still it's way better than before:

Example:
```php
        return [
            'highInitiative1'   =>
                [
                    'SPVL'           => '8.0',
                    'expectedLevel'  => new VulnerabilityLevel(VulnerabilityLevel::HIGH),
                    'exception'      => false,
                    'exceptionClass' => '',
                ],
            'highInitiative2'   =>
[...]
```
leads to
```
 197 | ERROR | [x] Expected 1 space after "=>"; newline found
 204 | ERROR | [x] Expected 1 space after "=>"; newline found
[...]
```

We should maybe force in one of our array sniffs that
`=> [` should be used in such a case insetad of `=> \n [`.

**Comment by xalopp** [comment]
Setting [OperatorSpacingSniff::ignoreNewlines](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php#L34) to `true` should do the trick.

**Comment by mmoll** [comment]
I think the sniff itself with ignoreNewlines=false is correct, as I don't fancy the version with newlines. Only the message and proposed fix is not what I had in mind.

**Comment by xalopp** [comment]
MO4 allows

```php
$a =
    'my very long string or statement';
```

But when `ignoreNewlines` is `false`, this is no more valid, as a space is need after `=`.

**Comment by mmoll** [comment]
my preferred version would be also in that case:
```php
$a = '
my very long string or statement';
```
or rather
```php
$a = '
my very long string or statement
';
```
to resemble the single quotes like braces in multiline statements or arrays.

**Comment by xalopp** [comment]
I guess, the "newlines are allowed after assignments, double arrows and concat operator" rule is implicit.

The README.md points out "in arrays, the key and => operator must be on the same line"
and the concat sniff import
https://github.com/mayflower/mo4-coding-standard/blob/master/MO4/ruleset.xml#L25
point out that newline after assignment and operators are super fine :)

**Comment by Ma27** [comment]
@mmoll IIRC is the Symfony convention to use the heredoc syntax:

``` php
$foo = <<<EOF
text
and moar text
EOF;
```

(just had a look at the Symfony3 codebase and it seems as they're still using this for their newline strings)

**Comment by mmoll** [comment]
> @mmoll IIRC is the Symfony convention to use the heredoc syntax:

Yeah, the string example is a rather theoretical one.
