### ISSUE TITLE
"USE statements must be sorted alphabetically"

### ISSUE THREAD

**Issue by xalopp** [mayflower/mo4-coding-standard#5]
While I believe this to be sorted correctly

```
use Doctrine\ORM\Query;
use Doctrine\ORM\Query\Expr; 
use Doctrine\ORM\QueryBuilder;
```

the current implementation only accepts

```
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Query\Expr;
```

which looks odd.

**Comment by tremby** [comment]
For what it's worth, the latter is what you get when you run GNU sort over it.

(This makes things easy. In vim, for example, select the lines in visual-line mode and do `!sort` to sort them. Or if the lines are all in a single "paragraph", from anywhere in that block, type `!ipsort`.)

**Comment by mmoll** [comment]
I **think** SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses from https://github.com/slevomat/coding-standard does implement @xalopp's preferred way.

If this would be confirmed, we could steal some code there...

**Comment by tremby** [comment]
Further to my above note, I since learned that the behaviour of GNU sort actually depends on the currently set locale, in particular the value of `LC_COLLATE`. As such, it would be nice in my eyes if this sniff functioned the same way.

**Comment by mmoll** [comment]
@tremby That's indeed valuable background information. I don't think having a coding standard depend onto a locale setting is a good idea, but that means we need to have the behaviour of this Sniff configurable.
