### ISSUE TITLE
Should we wait for PHPCS 3.2.0 for the next major release?

### ISSUE THREAD

**Issue by xalopp** [mayflower/mo4-coding-standard#55]
PHPCS 3.2.0 will introduce some nice features like:
* setting sniff properties with `// phpcs:set` comment. This is useful for testing an helps to increase the code coverage
* the new sniff `Generic.Arrays.ArrayIndent ` will handle some of the array indentation issues

This will imply, that `composer.json` will require phpcs version greater or equal than `3.2.0`

**Comment by mmoll** [comment]
3.2.0 got released 🎉
