### ISSUE TITLE
PROPOSAL: there should be a blank line before and after every if or for, while...

### ISSUE THREAD

**Issue by ritters** [mayflower/mo4-coding-standard#7]
only exception: when one of these keywords is in the next line after another one there should not be a blank line.

excample 1:

``` php
$a ...

foreach () {.
    $c = ...
}

$b = ....

if (...) {
   for (...) {
        ....
    } 
}

while (....) {
    if (...) {
        ....
    }

    $f = ...
}
```

**Comment by xalopp** [comment]
A blank line before control structures may break readability.
In this case, it's perfectly clear that `$i` is related to the loop.
```
$i = 1;
while ($i < $j) {
     // ...

     $i++;
}
```

but when a blank line is introduced, `$i` might lose some context:

```
$i = 1;

while ($i < $j) {
     // ...

     $i++;
}
```

Wouldn't it be better to enforce a blank line after the control structures?

The Squiz ControlStructureSpacingSniff has a implemented a 'No blank line found after control structure' rule:

* https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
* https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc
* https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Tests/WhiteSpace/ControlStructureSpacingUnitTest.php

**Comment by calbrecht** [comment]
:+1:  for ritters proposal, imho better style is to declare variables at beginning of function anyway.

**Comment by mmoll** [comment]
this proposal was approved by the MO4 standardizing committee

**Comment by xalopp** [comment]
Comments are allowed before control structures, but need to be preceded by a blank line them self.

**Comment by ritters** [comment]
The MO4 standardizing committee decided that this enhancement should only check for blank lines before control structures. 
Blank lines after control structures should be checked by Squiz ControlStructureSpacingSniff as mentioned by @xalopp .

So we need to write an own sniff "BlankLineBeforControlStructures" and integrate Squiz ControlStructureSpacingSniff in our ruleset.

**Comment by mmoll** [comment]
I think we can just pull in Squiz.WhiteSpace.ControlStructureSpacingSniff now for our version 2 to have at least one part of this proposal satisfied?

**Comment by xalopp** [comment]
I would suggest, that even it's not fully implemented, the "blank line before control structure" is mentioned in the README.md.  In this case, the implementation would be rather a bug fix than a major breaking change 😈

**Comment by xalopp** [comment]
I'll need to investigate when  `Squiz.WhiteSpace.ControlStructureSpacing` disallows blank lines after the begin of a control structure, and how this can conflict a nested control structure, e.g.:

```php
if ($boolA) {
    
    if ($boolB) {
    }
}
```

which should be valid, if I get it right

**Comment by calbrecht** [comment]
```
if ($squareBracketDepth === 0) {
    if ($char === '.') {
        if ($this->lookAhead($i, 1) === ".") {
```
vs.
```
if ($squareBracketDepth === 0) {

    if ($char === '.') {

        if ($this->lookAhead($i, 1) === ".") {
```
to have an actual real-world example at hand. Imho the lines between makes it more readable.

**Comment by xalopp** [comment]
@calbrecht Am I getting right, that both are valid in MO4 in your opinion?

**Comment by calbrecht** [comment]
No, i'd say the second is valid and the first is invalid.

**Comment by mmoll** [comment]
As it tuens out, part of this is also already standard per PSR2.

**Comment by xalopp** [comment]
And we should keep an eye on what PSR12 says about [Control Structures](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#5-control-structures)

**Comment by mmoll** [comment]
https://github.com/slevomat/coding-standard#slevomatcodingstandardcontrolstructurescontrolstructurespacing- suits this job, probably.

**Comment by Ma27** [comment]
am I getting it right that this sniff always wants a blank line before $token? Because I'm not entirely convinced yet that this doesn't break readability in some cases.

**Comment by mmoll** [comment]
Yes, we still need to check configurable options and/or possible extensions.

**Comment by mmoll** [comment]
So, for $customer, we use `SlevomatCodingStandard.ControlStructures.ControlStructureSpacing` with its defaults and it seems OK. Could any of the interested parties check if this would be the way to go? Then I'd include it in GH-126

**Comment by mmoll** [comment]
https://github.com/slevomat/coding-standard/issues/633 would be needed otherwise.

**Comment by mmoll** [comment]
The recent Slevomat issue got closed... Any opinions?

**Comment by Ma27** [comment]
As the original discussion occurred a while a ago, do all members agree on the proposal (or any alternative?). If so, I'd simply use the sniff with some customizations we've agreed on :)

**Comment by mmoll** [comment]
Then I'd still be happy to get a "known good" file with all of the edge cases in order to be able to configure the sniff.
