### ISSUE TITLE
Establish coding standard for MO4 sniffs

### ISSUE THREAD

**Issue by mmoll** [Mayflower/mo4-coding-standard#8]
The README states, PEAR should be used as standard, but there are a few files that are not passing the PEAR test currently. Which coding standard should be used here?

**Comment by xalopp** [comment]
Since PHPCS self uses the standard "PHPCS", the MO4-Standard itself should comply to PHPCS.

README must be updated and the code needs to be fixed.

**Comment by mmoll** [comment]
Thanks, I'll handle that.

**Comment by xalopp** [comment]
:thumbsup:
