### ISSUE TITLE
Check that PHP system-functions are prefixed with backslash

### ISSUE THREAD

**Issue by SebTM** [mayflower/mo4-coding-standard#80]
As found out by @Roave PHP system-functions (functions integrated into php) prefixed with a backslash to have an absolute reference to the used function makes a performance difference. We should consider implementing a check and fixer for this.

Sources & Benchmark: https://github.com/Roave/FunctionFQNReplacer

**Comment by xalopp** [comment]
This has been implemented in
https://github.com/slevomat/coding-standard#slevomatcodingstandardnamespacesfullyqualifiedglobalfunctions-
