### ISSUE TITLE
autofixing is missing for ArrayDoubleArrowAlignmentSniff 

### ISSUE THREAD

**Issue by xalopp** [mayflower/mo4-coding-standard#91]
A source of inspiration might be:

* https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php
* https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Squiz/Sniffs/Arrays/ArrayDeclarationSniff.php
* https://github.com/spryker/code-sniffer/blob/master/Spryker/Sniffs/Formatting/ArrayDeclarationSniff.php

**Comment by mmoll** [comment]
Maybe the `MO4.Array.*` Sniffs can get replaced with `Squiz.Arrays.ArrayDeclaration` alltogether now?

**Comment by xalopp** [comment]
@mmoll unfortunately not, because of the hard coded required indentation of arrays in the `Squiz.Arrays.ArrayDeclaration` which is not Symfony compatible 😢

**Comment by mmoll** [comment]
meh, OK
