### ISSUE TITLE
Code coverage of tests should be 100%

### ISSUE THREAD

**Issue by xalopp** [mayflower/mo4-coding-standard#96]
To increase confidence, we should look to have a code coverage of 💯

**Comment by Ma27** [comment]
sounds reasonable. But I'm not sure if entirely convinced about this as I remember some PHPUnit-related issues where i.e. a closing bracket was untested code, so I couldn't reach 100% coverage in some side-projects back then. But please correct me if I'm wrong, I didn't do too much PHP in the last year :smile:

**Comment by mmoll** [comment]
I did have a look into the coverage HTML report and IIRC there is indeed one line (or condition?) that's currently not tested.
